pipelines:
 - name: Sleep
   configuration:
   runtime:
    type: host
steps:
  - name: First_Step
    type: Bash
    execution:
      onExecute:
        - sleep 50
  - name: Second_Step
    type: Bash
    configuration:
      inputSteps:
        - name: First_Step
    execution:
      onExecute:
        - sleep 500
  - name: Third_Step
    type: Bash
    configuration:
      inputSteps:
        - name: Second_Step
    execution:
      onExecute:
        - sleep 1000
  - name: Fourth_Step
    type: Bash
    configuration:
      inputSteps:
        - name: Third_Step
    execution:
      onExecute:
        - sleep 2000
