pipelines:
- name: sleep2
  steps:
  - name: First_Step
    type: Bash
    execution:
      onExecute:
        - sleep 1
  - name: Second_Step
    type: Bash
    configuration:
      inputSteps:
        - name: First_Step
    execution:
      onExecute:
        - sleep 1
  - name: Third_Step
    type: Bash
    configuration:
      inputSteps:
        - name: Second_Step
    execution:
      onExecute:
        - sleep 1
  - name: Fourth_Step
    type: Bash
    configuration:
      inputSteps:
        - name: Third_Step
    execution:
      onExecute:
        - sleep 1
